# Generated by Django 3.0.14 on 2022-04-18 05:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation_details', '0006_auto_20220418_1113'),
        ('employees', '0007_auto_20220418_1113'),
        ('contacts', '0012_auto_20220418_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('qty', models.IntegerField(blank=True, default=None, null=True)),
                ('tax', models.IntegerField(blank=True, default=None, null=True)),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=200)),
                ('create_date', models.DateField(null=True)),
                ('contract_date', models.DateField(null=True)),
                ('apply_country', django_countries.fields.CountryField(max_length=2)),
                ('contract_status', models.CharField(choices=[('Draft Contract', 'Draft Contract'), ('Working For Apparel', 'Working For Apparel'), ('Confermation', 'Confermation'), ('Done', 'Done')], max_length=200)),
                ('service_type', models.CharField(choices=[('Business Visa', 'Business Visa'), ('Vsit Visa', 'Vsit Visa'), ('Investor Visa', 'Investor Visa'), ('Permanent Residency', 'Permanent Residency'), ('Work Permit', 'Work Permit')], max_length=200)),
                ('contract_template', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract2.Product')),
                ('sales_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.Team')),
                ('salesmen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
