# Generated by Django 3.2.9 on 2022-04-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='service_status',
            new_name='service_Package',
        ),
    ]
