# Generated by Django 3.2.9 on 2022-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract2', '0003_rename_contract_product_contract_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contract',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='other_info',
            name='contract',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='contract_no',
            field=models.CharField(max_length=200),
        ),
    ]
