# Generated by Django 3.2.9 on 2022-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract2', '0004_auto_20220422_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Additional_Documen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='CV_Resum',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='Emirates_ID',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='Ntional_ID',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='Passpost_Scan_Copy',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
