# Generated by Django 3.2.9 on 2022-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract2', '0005_auto_20220422_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_info',
            name='fiscal_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
