# Generated by Django 4.0.3 on 2022-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_currency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(default='AED', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='desc',
            field=models.CharField(default='United Arab Emirates Dirham', max_length=20),
        ),
    ]
