# Generated by Django 4.0.3 on 2022-04-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
