# Generated by Django 4.0.3 on 2022-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0002_remove_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_deposit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_deposit',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_due',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
