# Generated by Django 3.0.14 on 2022-04-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice1', '0005_alter_invoice_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
